version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(⬆️deps):'
    assignees:
      - 'shanpriyan'
    open-pull-requests-limit: 2
    rebase-strategy: auto
